import type { Metadata } from "next";
import Sidebar from "@/components/sidebar/Sidebar";
import Header from "@/components/header/Header";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Task App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/auth/signIn");
  }
  return (
    <>
      <div className="flex">
        <Header />
        <div className="flex">
          <Sidebar />
          <div style={{ marginLeft: 255, width: "calc(100vw - 255px)" }}>
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
